# Generated by Django 3.2.4 on 2021-06-13 16:18

from django.db import migrations, models
import j.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('activity', models.CharField(max_length=1000)),
                ('image', models.ImageField(blank=True, null=True, upload_to=j.models.get_file_path)),
                ('responce', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(max_length=100)),
                ('mobilenumber', models.IntegerField()),
            ],
        ),
    ]
