# Generated by Django 3.2.4 on 2021-06-13 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('j', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Activities',
            new_name='Activity',
        ),
    ]
