# Generated by Django 3.2.4 on 2021-06-19 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j', '0002_rename_activities_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobilenumber',
            field=models.CharField(max_length=100),
        ),
    ]
