# Generated by Django 3.2.4 on 2021-06-19 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('j', '0003_alter_member_mobilenumber'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='mobilenumber',
            field=models.BigIntegerField(),
        ),
    ]
